import type { Metadata } from "next";
import { Oxygen } from "next/font/google";
import Navbar from "./_components/layout/Navbar";
import "./globals.css";
import Footer from "./_components/layout/Footer";

const oxygen = Oxygen({
  subsets: ["latin"],
  weight: ["300","400", "700"],
})
export const metadata: Metadata = {
  title: "E-commerce Website with Next.js | Route Final Assignment",
  description: "E-commerce website generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${oxygen.className} antialiased`}>
        <Navbar />
        <main className="min-h-screen">
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
