import type { Metadata } from "next";
import { Oxygen } from "next/font/google";
import Navbar from "./_components/layout/Navbar";
import "./globals.css";
import Footer from "./_components/layout/Footer";
import { getAllCategories } from "@/lib/categories";
import { Toaster } from "@/components/ui/sonner";

const oxygen = Oxygen({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
})
export const metadata: Metadata = {
  title: "E-commerce Website with Next.js | Route Final Assignment",
  description: "E-commerce website generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await getAllCategories();
  return (
    <html lang="en">
      <body className={`${oxygen.className} antialiased`}>
        <Navbar categories={data} />
        <main className="min-h-screen">
          {children}
        </main>
        <Footer />
        <Toaster position="top-right"/>
      </body>
    </html>
  );
}
