import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { Oxygen } from "next/font/google";
import Footer from "./_components/layout/Footer";
import Navbar from "./_components/layout/Navbar";
import "./globals.css";
import Providers from "../lib/Providers";
import { getAllBrands, getAllCategories } from "@/lib/api";
import { Suspense } from "react";

const oxygen = Oxygen({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
})
export const metadata: Metadata = {
  title: "E-commerce Website with Next.js | Route Final Assignment",
  description: "E-commerce website generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categories = await getAllCategories();
  const brands = await getAllBrands();
  return (
    <html lang="en">
      <body className={`${oxygen.className} antialiased`}>
        <Providers>
          <Navbar categories={categories} brands={brands} />
          <Suspense fallback={<div>Loading...</div>}>
            <main className="min-h-screen">
              {children}
            </main>
          </Suspense>
          <Footer />
          <Toaster position="top-right" />
        </Providers>
      </body>
    </html>
  );
}
